//HintName: EndpointGenerator.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/EndpointGenerator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS8019
using global::Microsoft.AspNetCore.Builder;
using global::Microsoft.AspNetCore.Http;
using global::Microsoft.AspNetCore.Routing;
#pragma warning restore CS8019

namespace Microsoft.Extensions.DependencyInjection
{
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
	internal static class EndpointExtensions
	{
		public static IEndpointRouteBuilder MapEndpointGeneratorTest(this IEndpointRouteBuilder builder)
		{
			global::Accessibility.PublicMap(builder);
			global::Accessibility.InternalMap(builder);
			global::Accessibility.ProtectedInternalMap(builder);
			global::Accessibility.PublicGroupMap(builder.MapGroup("").WithName("Accessibility"));
			global::Accessibility.InternalGroupMap(builder.MapGroup("").WithName("Accessibility"));
			global::Accessibility.ProtectedInternalGroupMap(builder.MapGroup("").WithName("Accessibility"));
			return builder;
		}
	}
}
