//HintName: EndpointGenerator.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/distantcam/EndpointGenerator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable CS8019
using global::Microsoft.AspNetCore.Builder;
using global::Microsoft.AspNetCore.Http;
using global::Microsoft.AspNetCore.Routing;
#pragma warning restore CS8019

namespace Microsoft.Extensions.DependencyInjection
{
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
	internal static class EndpointExtensions
	{
		public static IEndpointRouteBuilder MapEndpointGeneratorTestEndpoints(this IEndpointRouteBuilder builder)
		{
			var group0 = builder.MapGroup("").WithName("Multiple1").WithTags("Multiple");
			global::Multiple.Multiple1.GroupMap(group0);
			var group1 = builder.MapGroup("").WithName("Multiple2").WithTags("Multiple");
			global::Multiple.Multiple2.GroupMap(group1);
			var group2 = builder.MapGroup("").WithName("Multiple3").WithTags("Multiple");
			global::Multiple.Multiple3.GroupMap(group2);
			var group3 = builder.MapGroup("").WithName("Multiple4").WithTags("Multiple");
			global::Multiple.Multiple4.GroupMap(group3);
			return builder;
		}
	}
}
